# Generate age private key:
# mkdir -p ~/.config/sops/age
# age-keygen -o ~/.config/sops/age/keys.txt

# Generate age public key: 
# age-keygen -y ~/.config/sops/age/keys.txt

# Generate a host key from SSH: 
# cat ~/.ssh/id_ed25519.pub | ssh-to-age

# Add secrets
# sops secrets/secrets.yaml

# Re-key secrets file after updating keys
# sops updatekeys secrets/secrets.yaml
keys:
  - &defiant age1jwra0w843dt6gjenzwnypenwhjuf4tl2uchxuyx4wy274h5qau4qq6e20z
  - &jarvis age1cu8qmzxu0lghgn80yuxpm8eu3t74tcrpldlexh5lfshjedactsmqpju3rc
  - &rocinante age1yj5qlrqjukxraa5mm9d4rn773w0nteame37p2z9y52ud6f0hrytqxqgccj
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *defiant
      - *jarvis
      - *rocinante
