keys:
  - &user_craig age1a857ekjalql7s7h55h4k9gh5mzfezua3qnldwn4zdn6dx2nmkvxsj2vjpm
  - &host_defiant age1jwra0w843dt6gjenzwnypenwhjuf4tl2uchxuyx4wy274h5qau4qq6e20z
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *user_craig
          - *host_defiant
